"""add phone number

Revision ID: 04898c809528
Revises: 627a690055b8
Create Date: 2023-07-07 12:29:26.784280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04898c809528'
down_revision = '627a690055b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
